### ISSUE TITLE
Observation

### ISSUE THREAD

**Issue by onuigwevitus** [JUGG097/Tuberculosis-Classification-via-X-Rays#1]
Thanks for sharing this nice notebook. I noticed the chest x-ray was flip, that's 90-degree rotation was applied. It may not affect the outcome of this investigation, but it will affect the outcome if you use the same method for other anomalies of the chest x-ray. The maximum rotation allowed for a chest x-ray is 15-degree.

**Comment by JUGG097** [comment]
Which images were flipped 90-degrees, the ones in the training set??

**Comment by onuigwevitus** [comment]
Yeah, I think it's from the training set. If I'm not mistaken, the flipped is actually 180-degrees. However, If it's not from you, then it's from the original datasets. 

I was able the only see the images with your code 
## Give a preview of the images loaded
dls.show_batch()

**Comment by JUGG097** [comment]
Okay, i agree with you rotating by 180-degrees (flipping) might affect outcome
